package com.quicktest.modules.session.entity;

import com.quicktest.modules.assessment.entity.AnswerOption;
import com.quicktest.modules.assessment.entity.Question;
import jakarta.persistence.*;
import lombok.*;

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

/**
 * Candidate answer entity representing submitted responses for each question.
 */
@Entity
@Table(
    name = "candidate_answers",
    uniqueConstraints = {
        @UniqueConstraint(name = "uk_candidate_answers_attempt_question", columnNames = {"attempt_id", "question_id"})
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CandidateAnswer {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "attempt_id", nullable = false)
    private ExamAttempt examAttempt;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "question_id", nullable = false)
    private Question question;

    // For SINGLE_CHOICE and MULTIPLE_CHOICE questions
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(
        name = "candidate_selected_options",
        joinColumns = @JoinColumn(name = "candidate_answer_id"),
        inverseJoinColumns = @JoinColumn(name = "option_id")
    )
    @Builder.Default
    private Set<AnswerOption> selectedOptions = new HashSet<>();

    // For NUMERIC and ESSAY_TEXT questions
    @Column(columnDefinition = "TEXT")
    private String textAnswer; // Text answer or candidate input number string

    // Individual score awarded for this question
    private Double awardedScore;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    @Builder.Default
    private GradingStatus gradingStatus = GradingStatus.AUTO_GRADED;

    @Column(columnDefinition = "TEXT")
    private String teacherFeedback; // Teacher feedback / comment

    // Future AI enhancement fields
    private Double aiSimilarityScore; // Semantic similarity score (0.0 -> 1.0)
    @Column(columnDefinition = "TEXT")
    private String aiGradingExplanation; // Explanation generated by LLM
}
